# Generated by Django 4.1.6 on 2023-02-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team',
            new_name='teams',
        ),
    ]
